# Generated by Django 3.0.5 on 2020-04-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200405_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('author', models.CharField(max_length=25)),
                ('summary', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
