# Generated by Django 3.0.5 on 2020-04-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsarticle_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date_pub',
            field=models.DateField(default='2020-04-13'),
        ),
    ]
